# Commitizen Config
commitizen:
 name: 'mtg-vectors'
 customize:
   message_template: "{{change_type}}:{% if show_message %} {{message}}{% endif %}"
   example: 'edit: Modified a symbol or multiple symbols.'
   schema: "<type>: <body>"
   schema_pattern: "(edit|add|delete|routing|docs|style|test|refactor|fix|feat):(\\s.*)"
   bump_pattern: "^(edit|add|delete|routing|docs|style|test|refactor|fix|feat)"
   commit_parser: "^(?P<change_type>edit|add|delete|routing|docs|style|test|refactor|fix|feat):\\s(?P<message>.*)?",
   changelog_pattern: "^(edit|add|delete|routing|docs|style|test|refactor|fix|feat)?(!)?",
   change_type_map:
     edit: Edit
     add: Add
     delete: Delete
     routing: Routing
     docs: Docs
     style: Style
     test: Test
     refactor: Refactor
     fix: Fix
     feat: Feat
   bump_map:
     edit: PATCH
     add: MINOR
     delete: MINOR
     routing: MAJOR
     docs: PATCH
     style: PATCH
     test: PATCH
     refactor: PATCH
     fix: PATCH
     feat: MINOR
   change_type_order: ["BREAKING CHANGE", "feat", "fix", "refactor", "perf"]
   info_path: cz_customize_info.txt
   info: This is customized info
   questions:
   - type: list
     name: change_type
     choices:
     - value: edit
       name: 'edit: Modified a symbol or multiple symbols.'
     - value: add
       name: 'add: Added a symbol or multiple symbols.'
     - value: delete
       name: 'delete: Deleted a symbol or multiple symbols.'
     - value: routing
       name: 'routing: Updated the routing or naming conventions used for an existing symbol or symbols.'
     - value: docs
       name: 'docs: Updated repository documentation, comments, or notes.'
     - value: style
       name: 'style: Made changes that do not affect the meaning of code or any SVG files.'
     - value: test
       name: 'test: Added or modified existing tests.'
     - value: refactor
       name: 'refactor: Made code changes that are neither a bug-fix or a new feature.'
     - value: fix
       name: 'fix: Fixed a code bug or fixed an incorrect route or data file.'
     - value: feat
       name: 'feat: Introduced a new code related feature or a new category of vectors.'
     message: Select the type of change you are committing
   - type: input
     name: message
     message: Body.
   - type: confirm
     name: show_message
     message: Do you want to add body message in commit?
