name: Build Package and Docs

on:
  push:
    branches: [main]
    paths:
      - 'svg/set/**/*.svg'
      - 'watermark/set/**/*.svg'

jobs:
  optimize-svg:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Inkscape
      run: |
        sudo add-apt-repository ppa:inkscape.dev/stable
        sudo apt-get update
        sudo apt-get install inkscape

    - name: Install Node.js and npm
      uses: actions/setup-node@v3
      with:
        node-version: 'latest'

    - name: Install SVGO
      run: npm install -g svgo

    - name: Process SVG files with Inkscape
      run: |
        find svg/set -name "*.svg" -print0 | while IFS= read -r -d '' file; do
          inkscape "$file" --actions="page-fit-to-selection;export-plain-svg;export-filename:$file"
        done

    - name: Optimize SVG files with SVGO
      run: |
        find svg/set -name "*.svg" -print0 | while IFS= read -r -d '' file; do
          optimized_file="svg/set_optimized/$(echo "$file" | sed 's/svg\/set//')"
          mkdir -p "$(dirname "$optimized_file")"
          svgo -i "$file" -o "$optimized_file"
        done

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: 'build(svg): Format and optimize svg files'
        title: 'Action: Optimize Symbols'
        body: "# Triggered by: New Commit\n-----------\nRan automated SVG optimization and formatting."
        branch: svg-optimization
        base: main
