name: Optimize SVG Symbols

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'svg/set/**/*.svg'
      - 'watermark/set/**/*.svg'

jobs:
  optimize-svg:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install Inkscape, XVFB, GitHub CLI
    - name: Install Inkscape
      run: |
        sudo add-apt-repository ppa:inkscape.dev/stable
        sudo apt-get install -y inkscape xvfb gh

    # Process SVG files with Inkscape
    - name: Process SVG files with Inkscape
      run: |
        find svg/set -name "*.svg" -print0 | while IFS= read -r -d '' file; do
          echo "file-open:$file; select-all; page-fit-to-selection; export-plain-svg; export-filename:$file; file-close" >> commands.txt
        done
        xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" inkscape --shell < commands.txt
        rm commands.txt
        git add .

    # Install Node, NPM and SVGO
    - name: Install Node / NPM
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    # Create optimized versions of all SVG files
    - name: Install SVGO, Optimize SVG files
      run: |
        npm install -g svgo
        find svg/set -name "*.svg" -print0 | while IFS= read -r -d '' file; do
          optimized_file="svg/set_optimized/$(echo "$file" | sed 's/svg\/set//')"
          mkdir -p "$(dirname "$optimized_file")"
          svgo -i "$file" -o "$optimized_file"
        done
        git add .

    # Create a PR with the changes, or update existing one
    - name: Update Existing PR or Create New One
      run: |
        # Extract the owner's username from the github.repository context
        REPO_OWNER=${{ github.repository_owner }}

        # Check if a PR exists for the svg-actions branch
        pr_exists=$(gh pr list --state=open --author=$REPO_OWNER --label=auto-generated --head=svg-actions)
        
        if [[ -n "$pr_exists" ]]; then
          echo "Existing PR found. Pushing changes to update..."
          git push origin svg-actions
        else
          echo "No existing PR found. Creating new PR..."
          git checkout -b svg-actions
          git add .
          git commit -m "build(svg): Format and optimize svg files"
          git push origin svg-actions
          
          gh pr create \
            --title "Action: Optimize Symbols" \
            --body "Triggered by: New Commit\n-----------\nRan automated SVG optimization and formatting." \
            --head svg-actions \
            --base main \
            --label auto-generated
        fi
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}