name: Optimize SVG Symbols

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'svg/set/**/*.svg'
      - 'watermark/set/**/*.svg'

jobs:
  optimize-svg:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install Inkscape, XVFB, GitHub CLI
    - name: Install Inkscape
      run: |
        sudo add-apt-repository ppa:inkscape.dev/stable
        sudo apt-get install -y inkscape xvfb gh

    # Process SVG files with Inkscape
    - name: Process SVG files with Inkscape
      run: |
        find svg/set -name "*.svg" -print0 | while IFS= read -r -d '' file; do
          echo "file-open:$file; select-all; page-fit-to-selection; export-plain-svg; export-filename:$file; export-do; file-close" >> commands.txt
        done
        xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" inkscape --shell < commands.txt
        rm commands.txt
        git add .

    # Install Node, NPM and SVGO
    - name: Install Node / NPM
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    # Create optimized versions of all SVG files
    - name: Install SVGO, Optimize SVG files
      run: |
        npm install -g svgo
        find svg/set -name "*.svg" -print0 | while IFS= read -r -d '' file; do
          optimized_file="svg/set_optimized/$(echo "$file" | sed 's/svg\/set//')"
          mkdir -p "$(dirname "$optimized_file")"
          svgo -i "$file" -o "$optimized_file"
        done
        git add .

    # Create a PR
    - name: Update Existing PR or Create New One
      run: |
        # Configure Git user
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
    
        # Checkout to the target branch, create it if it doesn't exist
        git checkout -b actions/svg-optimize || true
    
        # Commit changes
        git add .
        git commit -m "build(svg): Format and optimize svg files"
    
        # Push changes to the remote repository
        git pull
        git push -u origin actions/svg-optimize
    
        # Check if a PR exists for the actions/svg-optimize branch
        pr_json=$(gh pr list --state open --label auto-generated --head actions/svg-optimize --json number)
        pr_number=$(echo "$pr_json" | jq -r '.[0].number')
    
        if [[ -n "$pr_exists" ]]; then
          echo "Existing PR found, no need to make one"
        else
        # Create a new PR
          echo "No existing PR found. Creating new PR"
          gh pr create \
            --title "Action: Optimize Symbols" \
            --body "Triggered by: New Commit\r\n-----------\r\nRan automated SVG optimization and formatting." \
            --head actions/svg-optimize \
            --base main \
            --label auto-generated
        fi
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}